apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: oam-test
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - environment: staging
      - environment: production
  template:
    metadata:
      name: '{{environment}}-oam-test'
    spec:
      project: default
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
      source:
        repoURL: https://github.com/jamesw201/oam-test.git
        targetRevision: HEAD
        path: "/"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{environment}}'