apiVersion: v1
kind: ConfigMap
metadata:
  name: vela-kubeconfig
  namespace: argocd
data:
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyTlRRMU1ETXdOekl3SGhjTk1qSXdOakEyTURneE1URXlXaGNOTXpJd05qQXpNRGd4TVRFeQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyTlRRMU1ETXdOekl3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTTHJtYW9SOHZQdEhwdWluNlk0UHR5MFhkWm9iZ1lvRUk5T25kNWc5SmIKR01FYnV0MzZ5b3UwQWFGbGJqVWVFc3RJcmM1Y0RXWE1tQVp5ZlVXcWpxaXlvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVo5VU9XL2U2UExNS2dLNFkxait2CnJweFpmN0V3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnVktvMGlCL054aE03d1VBa3NOUmRVRDk0RzB3MDV4djgKU0JDWWJaVTQ1TE1DSVFEMlFkK1NsVmlYS1hiVHcyMGtzcU1Lb0NyNng0ZThiOUdxaGJTY2RRdEZpQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        server: https://0.0.0.0:54788
      name: k3d-k3s-default
    contexts:
    - context:
        cluster: k3d-k3s-default
        user: admin@k3d-k3s-default
      name: k3d-k3s-default
    current-context: k3d-k3s-default
    kind: Config
    preferences: {}
    users:
    - name: admin@k3d-k3s-default
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJSXoyZTRWNGpHL013Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOalUwTlRBek1EY3lNQjRYRFRJeU1EWXdOakE0TVRFeE1sb1hEVEl6TURZdwpOakE0TVRFeE1sb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJHUDF1Y0xaZVNOMmVXKzEKcnkrQ2sxeE9XMmNXK08xNWRMaW1uZGtMYjZjMjM2bVhyaDVsV01KNTdxd3JWaFNtcGFIaTFPVm9ybHlISFpULwpNMHpwKzZxalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCVGxHd1IyVUMwUlprY2NERkJXMk9OaUkwUENCREFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlFQTZJQ1kyaDNtaGJQZ2VBSkN6cHN5ZEtvQ2k5MDRRcUtxNWFGalBseHNIOVFDSUZrWlpjeWtYTEpXQU9NbAo5dC9Xc1BwRmduWEpSTDJMeXlpUEtHWjUzcW80Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUyTlRRMU1ETXdOekl3SGhjTk1qSXdOakEyTURneE1URXlXaGNOTXpJd05qQXpNRGd4TVRFeQpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUyTlRRMU1ETXdOekl3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTZmtweGVIVmtUVTdxbjNHKzRTTkxDU0FKK0NBZnYyU1NLWkdiVFVYZUEKVFBQZUtCNnpTMHNJT3RJUkxNVU5jQkNSMzlyemJ0eGl3aVlOb3pDNERXWWdvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVTVSc0VkbEF0RVdaSEhBeFFWdGpqCllpTkR3Z1F3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU11ZHl5MHNPR0hyOGhiYjY5Y0tZOVprRFpIdFQ2WmEKS2RqRlhwaXFXVjVSQWlBVEpYTjFqZGZuK2d3VFRsRlJid3FjcEFMTm45dWJuTURVMlFwYTRGREVMZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUhhWjZPcjBlL0t3OUtsc250NTdPZVpXOXZROXo2L1c4NTk2T1FCSlRFNXZvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFWS9XNXd0bDVJM1o1YjdXdkw0S1RYRTViWnhiNDdYbDB1S2FkMlF0dnB6YmZxWmV1SG1WWQp3bm51ckN0V0ZLYWxvZUxVNVdpdVhJY2RsUDh6VE9uN3FnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
